#!/usr/bin/env python3
"""
ISS Isospin Block Analysis
--------------------------
Computes F-term equations for the 2x2 (u,d) isospin block of the ISS meson matrix,
analyzes eigenvalue structure, and determines whether ISS projects onto Tr(M_iso).
"""

import numpy as np

print("=" * 70)
print("PART 1: F-TERM EQUATIONS — OFF-DIAGONAL ENTRIES VANISH")
print("=" * 70)
print()
print("Superpotential:")
print("  W = h Tr(mu_hat M) + h X (det M - B Btilde - Lambda^6)")
print("  mu_hat = diag(mu_u, mu_d, mu_s, mu_c)")
print()
print("F-term equations:")
print("  F_X = 0  =>  det(M) = B Btilde + Lambda^6")
print("  F_B = 0  =>  X Btilde = 0")
print("  F_Bt = 0 =>  X B = 0")
print("  F_{M_ij} = 0  =>  mu_hat_{ij} + X * [adj(M)]_{ji} = 0")
print()
print("CASE X != 0 (Seiberg vacuum):")
print("  B = Btilde = 0  =>  det(M) = Lambda^6")
print()
print("Consider M block-diagonal: M = diag(M_iso, M_ss, M_cc)")
print("where M_iso = [[M_uu, M_ud], [M_du, M_dd]]")
print("(justified: SU(2)_iso and (s,c) sectors decouple at tree level)")
print()
print("det(M) = (M_uu M_dd - M_ud M_du) * M_ss * M_cc")
print()
print("F-term for M_ud (off-diagonal, mu_hat has no (u,d) entry):")
print("  F_{M_ud} = 0 + X * d(det M)/dM_ud = X * (-M_du) * M_ss * M_cc = 0")
print("  Since X != 0, M_ss != 0, M_cc != 0:")
print()
print("  *** M_du = 0 ***")
print()
print("Similarly, F_{M_du} = X * (-M_ud) * M_ss * M_cc = 0  =>")
print()
print("  *** M_ud = 0 ***")
print()
print("QED: Off-diagonal entries of the isospin block vanish classically.")
print("The meson matrix is DIAGONAL at the F-term vacuum.")
print()

print("Diagonal F-terms (with M_ud = M_du = 0):")
print("  F_{M_uu}: mu_u + X * M_dd * M_ss * M_cc = 0")
print("  F_{M_dd}: mu_d + X * M_uu * M_ss * M_cc = 0")
print("  F_{M_ss}: mu_s + X * M_uu * M_dd * M_cc = 0")
print("  F_{M_cc}: mu_c + X * M_uu * M_dd * M_ss = 0")
print()
print("Ratio of first two equations:")
print("  mu_u/mu_d = (M_dd * M_ss * M_cc) / (M_uu * M_ss * M_cc) = M_dd/M_uu")
print()
print("General solution: M_jj = C / mu_j  where  C = (Lambda^6 prod(mu))^{1/4}")
print()
print("CROSS-ASSIGNMENT (seesaw):")
print("  M_uu ~ 1/mu_u  (NOT proportional to mu_u)")
print("  M_dd ~ 1/mu_d")
print()
print("In the electric description, mu_j ~ m_j (quark mass), so")
print("  <M_jj> ~ Lambda^2/m_j")
print()

print("=" * 70)
print("PART 2: EIGENVALUES AND THE LIMIT mu_u -> 0")
print("=" * 70)
print()
print("Since M_iso is diagonal with VEVs:")
print("  M_uu = C/mu_u,   M_dd = C/mu_d")
print()
print("Eigenvalues = {C/mu_u, C/mu_d}")
print()
print("As mu_u -> 0:")
print("  M_uu -> infinity (diverges)")
print("  C = (Lambda^6 mu_u mu_d mu_s mu_c)^{1/4} -> 0")
print("  M_uu = C/mu_u = (Lambda^6 mu_d mu_s mu_c / mu_u^3)^{1/4} -> infinity")
print("  M_dd = C/mu_d = (Lambda^6 mu_u mu_s mu_c / mu_d^3)^{1/4} -> 0")
print()
print("So one eigenvalue diverges, the other vanishes.")
print("The TRACE = M_uu + M_dd diverges.")
print("The DETERMINANT = C^2/(mu_u mu_d) = (Lambda^6 mu_s mu_c)^{1/2} -> finite")
print()
print("This means: in the chiral limit, the isospin block does NOT naturally")
print("project onto a finite 'Tr(M_iso)' — it diverges.")
print()

print("=" * 70)
print("PART 3: NUMERICAL KOIDE ANALYSIS")
print("=" * 70)
print()

# PDG quark masses (MS-bar at 2 GeV, in MeV)
m_u = 2.16   # +0.49 -0.26
m_d = 4.67   # +0.48 -0.17
m_s = 93.4   # +8.6 -3.4
m_c = 1270.0 # at m_c
m_b = 4180.0 # at m_b
m_t = 172500.0 # pole

def koide_Q(m1, m2, m3):
    """Compute Koide quotient Q = (m1+m2+m3)/(sqrt(m1)+sqrt(m2)+sqrt(m3))^2"""
    s = np.sqrt(m1) + np.sqrt(m2) + np.sqrt(m3)
    return (m1 + m2 + m3) / s**2

print("Option (a): individual quarks (u, d, s)")
Q_a = koide_Q(m_u, m_d, m_s)
print(f"  Q(m_u, m_d, m_s) = {Q_a:.6f}  (deviation from 2/3: {abs(Q_a - 2/3)/(2/3)*100:.2f}%)")
print()

print("Option (b): (0, m_u+m_d, m_s) — zero + isospin trace + strange")
Q_b = koide_Q(0, m_u + m_d, m_s)
print(f"  Q(0, m_u+m_d, m_s) = {Q_b:.6f}  (deviation from 2/3: {abs(Q_b - 2/3)/(2/3)*100:.2f}%)")
print()

print("Option (c): (m_u, m_u+m_d, m_s)")
Q_c = koide_Q(m_u, m_u + m_d, m_s)
print(f"  Q(m_u, m_u+m_d, m_s) = {Q_c:.6f}  (deviation from 2/3: {abs(Q_c - 2/3)/(2/3)*100:.2f}%)")
print()

print("Option (b') using pion mass squared as proxy:")
print("  m_pi = 139.57 MeV, so m_pi^2 = 19480 MeV^2")
print("  B_0 = m_pi^2/(m_u+m_d) = {:.0f} MeV".format(139.57**2 / (m_u + m_d)))
print("  This is a derived quantity, not an independent mass parameter.")
print()

# Also check the MESON Koide (seesaw image)
print("Seesaw image: M_j ~ 1/m_j")
print("  1/m_u = {:.4f}, 1/m_d = {:.4f}, 1/m_s = {:.6f}".format(1/m_u, 1/m_d, 1/m_s))
Q_inv = koide_Q(1/m_u, 1/m_d, 1/m_s)
print(f"  Q(1/m_u, 1/m_d, 1/m_s) = {Q_inv:.6f}  (deviation from 2/3: {abs(Q_inv - 2/3)/(2/3)*100:.2f}%)")
print()

# Check dual Koide for (u,d,s) with 1/m
print("Dual Koide (inverse masses):")
Q_dual_uds = koide_Q(1/m_u, 1/m_d, 1/m_s)
Q_dual_dsc = koide_Q(1/m_d, 1/m_s, 1/m_c)
Q_dual_dsb = koide_Q(1/m_d, 1/m_s, 1/m_b)
print(f"  Q(1/m_u, 1/m_d, 1/m_s) = {Q_dual_uds:.6f}")
print(f"  Q(1/m_d, 1/m_s, 1/m_c) = {Q_dual_dsc:.6f}")
print(f"  Q(1/m_d, 1/m_s, 1/m_b) = {Q_dual_dsb:.6f}")
print()

print("=" * 70)
print("PART 4: GMOR RELATION AND ISS MESON M_ud")
print("=" * 70)
print()
print("In the ISS magnetic description, the meson field is M_{ij} ~ Q_i Qtilde_j / Lambda.")
print("The diagonal entries M_{uu}, M_{dd} correspond to <q_u qbar_u>, <q_d qbar_d>.")
print()
print("The GMOR relation involves <qbar q> = <qbar_u q_u + qbar_d q_d> = Tr(<M_iso>)")
print("  m_pi^2 f_pi^2 = -(m_u + m_d) <qbar q>")
print()
print("In ISS language:")
print("  <qbar q> ~ Lambda * Tr(M_iso) = Lambda * (M_uu + M_dd)")
print("           = Lambda * C * (1/mu_u + 1/mu_d)")
print("           = Lambda * C * (mu_u + mu_d)/(mu_u * mu_d)")
print()
print("So GMOR gives: m_pi^2 ~ (mu_u + mu_d) * Lambda * C * (mu_u + mu_d)/(mu_u * mu_d)")
print("             = Lambda * C * (mu_u + mu_d)^2 / (mu_u * mu_d)")
print()
print("This is NOT simply proportional to (mu_u + mu_d). It involves the ratio as well.")
print()
print("KEY POINT: The ISS seesaw INVERTS the mass hierarchy.")
print("  Tr(M_iso) = C/mu_u + C/mu_d = C(mu_u + mu_d)/(mu_u * mu_d)")
print()
print("This is proportional to (mu_u + mu_d)/(mu_u * mu_d) = 1/mu_d + 1/mu_u")
print("i.e., the sum of INVERSE masses, not the sum of masses.")
print()

print("=" * 70)
print("PART 5: SIGMA AND DELTA DECOMPOSITION")
print("=" * 70)
print()
print("Define: Sigma = M_uu + M_dd = C(1/mu_u + 1/mu_d)")
print("        Delta = M_uu - M_dd = C(1/mu_u - 1/mu_d)")
print()
print("In the superpotential W = h * (mu_u M_uu + mu_d M_dd) + h X det(M)...")
print()
print("Rewrite in terms of Sigma, Delta:")
print("  M_uu = (Sigma + Delta)/2,  M_dd = (Sigma - Delta)/2")
print()
print("  mu_u M_uu + mu_d M_dd = mu_u (Sigma+Delta)/2 + mu_d (Sigma-Delta)/2")
print("    = [(mu_u+mu_d)/2] Sigma + [(mu_u-mu_d)/2] Delta")
print()
print("  det(M_iso) = M_uu M_dd = (Sigma^2 - Delta^2)/4")
print("  det(M) = [(Sigma^2 - Delta^2)/4] * M_ss * M_cc")
print()
print("So W contains:")
print("  h * [(mu_u+mu_d)/2] * Sigma  +  h * [(mu_u-mu_d)/2] * Delta")
print("  + h X * [(Sigma^2 - Delta^2)/4] * M_ss * M_cc  + ...")
print()
print("The MASS TERMS for Sigma and Delta are:")
print("  Sigma couples to (mu_u + mu_d)/2  [isospin symmetric]")
print("  Delta couples to (mu_u - mu_d)/2  [isospin breaking]")
print()
print("In the ISOSPIN LIMIT mu_u = mu_d = mu:")
print("  Delta's linear coupling vanishes: (mu_u - mu_d)/2 = 0")
print("  Delta only appears through the det term: -X Delta^2 M_ss M_cc / 4")
print("  => Delta gets a mass from the det term but NO tadpole")
print("  => <Delta> = 0 in the isospin limit (from the quadratic potential)")
print()
print("  Sigma gets both a tadpole [(mu_u+mu_d)/2 = mu] AND the det coupling")
print("  => <Sigma> != 0")
print()
print("Away from the isospin limit (mu_u != mu_d):")
print("  Both Sigma and Delta get VEVs proportional to their respective tadpoles.")
print("  <Sigma> = C(1/mu_u + 1/mu_d),  <Delta> = C(1/mu_u - 1/mu_d)")
print("  Both are generically nonzero.")
print()
print("CONCLUSION ON SIGMA vs DELTA:")
print("The superpotential does NOT decouple Delta. Both Sigma and Delta")
print("have masses of order X * M_ss * M_cc (from the det term).")
print("In the isospin limit, Delta's VEV vanishes by symmetry, but")
print("Delta remains a physical degree of freedom with the same mass as Sigma.")
print()

print("=" * 70)
print("PART 5b: MASS MATRIX FOR FLUCTUATIONS")
print("=" * 70)
print()
print("Expand around vacuum M_jj = v_j = C/mu_j, fluctuations phi_j:")
print("  M_jj = v_j + phi_j")
print()
print("The F-term potential V = sum_j |dW/dM_jj|^2 + |dW/dX|^2 + ...")
print()
print("Second derivatives of det(M) = M_uu M_dd M_ss M_cc (diagonal M):")
print("  d^2(det M)/(dM_uu dM_dd) = M_ss M_cc")
print("  d^2(det M)/(dM_uu dM_ss) = M_dd M_cc")
print("  etc.")
print("  d^2(det M)/(dM_uu)^2 = 0  (det is multilinear)")
print()
print("In the (Sigma, Delta) basis, the mass matrix from the X-coupling:")
print("  d^2[det(M_iso)]/(dSigma^2) = 1/4 * d^2(Sigma^2-Delta^2)/dSigma^2 = 1/2")
print("  d^2[det(M_iso)]/(dDelta^2) = -1/2")
print("  d^2[det(M_iso)]/(dSigma dDelta) = 0")
print()
print("So in the (Sigma, Delta) basis, the X*det coupling gives a mass matrix")
print("proportional to diag(+1/2, -1/2) * X * M_ss * M_cc.")
print()
print("The cross-term vanishes: Sigma and Delta do NOT mix through the det potential.")
print("Both have the SAME magnitude mass |X M_ss M_cc / 2| but opposite signs.")
print("(The full mass matrix including F-term squares is positive definite.)")
print()

print("=" * 70)
print("PART 6: CHIRAL SYMMETRY AND SIGMA")
print("=" * 70)
print()
print("SU(2)_L x SU(2)_R chiral symmetry (for mu_u = mu_d = 0):")
print("  M_iso -> L M_iso R^dagger")
print("  Sigma = Tr(M_iso) is invariant under SU(2)_V (L=R)")
print("  but Tr(M_iso) is NOT invariant under SU(2)_A")
print()
print("Under SU(2)_V: M_iso -> U M_iso U^dagger, Tr -> Tr (invariant)")
print("  Sigma is a singlet under isospin SU(2)_V")
print("  Delta = M_uu - M_dd transforms as the 3-component of a triplet")
print()
print("Under FULL chiral SU(2)_L x SU(2)_R:")
print("  Sigma = Tr(M_iso) is the sigma (chiral singlet) mode")
print("  The off-diag (M_ud, M_du) and Delta form the pion triplet")
print()
print("HOWEVER: Koide analysis uses MASS EIGENVALUES, not symmetry representations.")
print("The mass eigenvalues of M_iso are the diagonal entries (since M_iso is diagonal),")
print("which are M_uu = C/mu_u and M_dd = C/mu_d — the individual seesaw masses.")
print()
print("Chiral symmetry relates to the CLASSIFICATION of fluctuations, not to VEVs.")
print("The VEV Tr(M_iso) = C/mu_u + C/mu_d probes the sum of inverse masses,")
print("not the sum m_u + m_d that appears in GMOR.")
print()

print("=" * 70)
print("PART 7: MECHANISM FOR m_u + m_d PROJECTION?")
print("=" * 70)
print()
print("The question: is there a natural mechanism in ISS that produces")
print("the combination (m_u + m_d) as a single effective parameter?")
print()
print("In the ELECTRIC description:")
print("  The quark mass term is W_mass = m_u u ubar + m_d d dbar")
print("  The isospin-symmetric combination is (m_u + m_d)/2 = m_iso")
print("  This appears in the condensate: <qbar q> * (m_u + m_d) = -f_pi^2 m_pi^2")
print()
print("In the MAGNETIC (ISS) description:")
print("  W = h mu_u M_uu + h mu_d M_dd + ...")
print("  = h [(mu_u+mu_d)/2] Sigma + h [(mu_u-mu_d)/2] Delta + ...")
print()
print("So (mu_u + mu_d) = (m_u + m_d) naturally appears as the coupling of Sigma.")
print()
print("BUT: the Koide quotient uses sqrt(mass), not mass.")
print("  Q(0, m_u+m_d, m_s) = 0.665 is close to 2/3")
print()
print("The question is: why would the Koide triple be (0, m_u+m_d, m_s)")
print("rather than (m_u, m_d, m_s)?")
print()
print("POSSIBLE MECHANISM: If one forms the triple from SU(2)_V representations:")
print("  - Sigma = Tr(M_iso) is a singlet with effective mass ~ mu_u + mu_d")
print("  - The pion triplet (off-diag + Delta) has mass ~ |mu_u - mu_d|/2")
print("  - M_ss is a singlet with mass mu_s")
print()
print("If Koide acts on the SINGLET spectrum: (pion mass, sigma mass, kaon mass)")
print("then the pion mass squared ~ (m_u + m_d) B_0 and kaon ~ (m_u + m_s) B_0")
print("But this mixes squared masses (mesons) with linear masses (quarks).")
print()

print("ACTUAL MECHANISM — CONFINEMENT + CHIRAL SYMMETRY BREAKING:")
print()
print("The combination (m_u + m_d) arises NOT from the ISS superpotential")
print("but from the PHYSICAL SPECTRUM after chiral symmetry breaking:")
print("  - The pion is the pseudo-Goldstone of SU(2)_A breaking")
print("  - Its mass-squared is m_pi^2 = (m_u + m_d) B_0  [GMOR]")
print("  - This is the LIGHTEST hadronic state")
print()
print("In a Koide analysis of MESON masses (not quark masses),")
print("the pion mass is the first-generation entry, and it naturally")
print("encodes (m_u + m_d) rather than m_u or m_d separately.")
print()
print("But this is a statement about the HADRONIC spectrum,")
print("not about the ISS superpotential directly.")
print()

print("=" * 70)
print("SUMMARY OF RESULTS")
print("=" * 70)
print()
print("1. CLASSICAL VACUUM: Off-diagonal M_ud = M_du = 0.")
print("   PROOF: F_{M_ud} = X * M_du * M_ss * M_cc = 0 with X,M_ss,M_cc != 0.")
print("   The meson VEVs are diagonal: <M_jj> = C/mu_j.")
print()
print("2. EIGENVALUES: {C/mu_u, C/mu_d}. As mu_u -> 0: M_uu -> inf, M_dd -> 0.")
print("   The trace diverges; the determinant stays finite.")
print()
print("3. SIGMA vs DELTA: The superpotential decomposes as:")
print("   W ~ [(mu_u+mu_d)/2] Sigma + [(mu_u-mu_d)/2] Delta + X(Sigma^2-Delta^2)/4 * M_ss M_cc")
print("   Both Sigma and Delta have comparable masses. Neither decouples.")
print("   In the isospin limit mu_u=mu_d: <Delta>=0 by symmetry, but Delta stays massive.")
print()
print("4. NO CLEAN ISS MECHANISM: The ISS superpotential does NOT naturally project")
print("   the (u,d) block onto (m_u+m_d). The seesaw gives individual VEVs C/mu_j.")
print("   The combination (m_u+m_d) enters through the sigma/Sigma coupling, but")
print("   this is the coupling constant of a field, not a mass eigenvalue.")
print()
print("5. GMOR CONNECTION: In the magnetic description, Tr(M_iso) ~ (1/mu_u + 1/mu_d),")
print("   which is proportional to (mu_u+mu_d)/(mu_u*mu_d) — the sum of INVERSE masses.")
print("   The sum (mu_u+mu_d) appears as the LINEAR coupling of Sigma, but this does")
print("   not directly produce (m_u+m_d) as a mass eigenvalue for Koide analysis.")
print()
print("6. CHIRAL SYMMETRY: SU(2)_V protects Sigma = Tr(M_iso) as a singlet.")
print("   But Koide analysis uses mass eigenvalues, not symmetry representations.")
print("   The combination (m_u+m_d) as an effective 'first-generation mass' for Koide")
print("   most naturally arises from the PION mass (m_pi^2 ~ (m_u+m_d)B_0),")
print("   which is a hadronic spectrum statement, not an ISS superpotential statement.")
print()
print("BOTTOM LINE: Option (b) with Q=0.665 works numerically, but the ISS does not")
print("provide a clean mechanism to replace (m_u, m_d) with (0, m_u+m_d) at the")
print("superpotential level. The projection onto (m_u+m_d) is a CHIRAL DYNAMICS")
print("effect (GMOR/pion), not an ISS magnetic-description effect. If one wants")
print("Koide to act on quark masses directly, Option (a) with Q=0.567 is what")
print("the ISS gives. Option (b) requires an additional physical input: that the")
print("relevant degree of freedom for the first generation is the pion, not")
print("individual u,d quarks.")
print()

# Additional numerical checks
print("=" * 70)
print("APPENDIX: ADDITIONAL NUMERICAL CHECKS")
print("=" * 70)
print()
print("Koide quotients for various triples:")
triples = [
    ("e, mu, tau", 0.511, 105.66, 1776.86),
    ("u, d, s", m_u, m_d, m_s),
    ("0, u+d, s", 0, m_u+m_d, m_s),
    ("d, s, b (inverse)", 1/m_d, 1/m_s, 1/m_b),
    ("-s, c, b", m_s, m_c, m_b),  # the known quark Koide
    ("c, b, t", m_c, m_b, m_t),
    ("0, u+d, s (Sigma projection)", 0, m_u + m_d, m_s),
    ("u+d, s, c", m_u+m_d, m_s, m_c),
    ("0, m_pi^2/B0, s  with B0=2.6GeV", 0, 139.57**2/2600, m_s),
]

for name, m1, m2, m3 in triples:
    Q = koide_Q(m1, m2, m3)
    dev = abs(Q - 2/3) / (2/3) * 100
    print(f"  Q({name:40s}) = {Q:.6f}  ({dev:.3f}% from 2/3)")

print()
print("Note: Q(0, m_u+m_d, m_s) = Q(0, 6.83, 93.4) = ", end="")
# Explicit calculation
m_sum = m_u + m_d
s = np.sqrt(0) + np.sqrt(m_sum) + np.sqrt(m_s)
Q_explicit = (0 + m_sum + m_s) / s**2
print(f"{Q_explicit:.8f}")
print(f"  2/3 = {2/3:.8f}")
print(f"  Difference = {Q_explicit - 2/3:.8f} ({abs(Q_explicit - 2/3)/(2/3)*100:.4f}%)")
print()

# What value of m_sum would give EXACT Koide?
# Q = (0 + m_sum + m_s) / (sqrt(m_sum) + sqrt(m_s))^2 = 2/3
# => 3(m_sum + m_s) = 2(sqrt(m_sum) + sqrt(m_s))^2 = 2(m_sum + 2*sqrt(m_sum*m_s) + m_s)
# => 3m_sum + 3m_s = 2m_sum + 4sqrt(m_sum*m_s) + 2m_s
# => m_sum + m_s = 4sqrt(m_sum*m_s)
# => let r = sqrt(m_sum/m_s), then r^2 + 1 = 4r => r^2 - 4r + 1 = 0
# => r = (4 +/- sqrt(12))/2 = 2 +/- sqrt(3)
# => sqrt(m_sum/m_s) = 2 - sqrt(3) [taking the smaller root, since m_sum < m_s]
# => m_sum/m_s = (2-sqrt(3))^2 = 7 - 4sqrt(3)

r_exact = 2 - np.sqrt(3)
m_sum_exact = r_exact**2 * m_s
print(f"For EXACT Koide Q=2/3 with triple (0, m_sum, m_s):")
print(f"  sqrt(m_sum/m_s) = 2 - sqrt(3) = {r_exact:.8f}")
print(f"  m_sum = (7 - 4sqrt(3)) * m_s = {m_sum_exact:.4f} MeV")
print(f"  Actual m_u + m_d = {m_u + m_d:.4f} MeV")
print(f"  Ratio actual/exact = {(m_u+m_d)/m_sum_exact:.6f}")
print(f"  Deficit = {((m_u+m_d) - m_sum_exact)/m_sum_exact * 100:.2f}%")
print()

# This is the Koide seed! (0, 2-sqrt(3), 2+sqrt(3)) normalized to (0, m_sum, m_s)
print("Note: The exact Koide condition Q=2/3 for (0, x, y) requires")
print("  sqrt(x/y) = 2 - sqrt(3)  or  sqrt(x/y) = 2 + sqrt(3)")
print("This is exactly the Koide SEED ratio (0, 2-sqrt(3), 2+sqrt(3))!")
print(f"  (2-sqrt(3))^2 = {(2-np.sqrt(3))**2:.8f}")
print(f"  (2+sqrt(3))^2 = {(2+np.sqrt(3))**2:.8f}")
print(f"  m_s/m_sum = {m_s/(m_u+m_d):.4f}")
print(f"  (2+sqrt(3))^2/(2-sqrt(3))^2 = {((2+np.sqrt(3))/(2-np.sqrt(3)))**2:.4f}")
print(f"  = (2+sqrt(3))^4 = {(2+np.sqrt(3))**4:.4f}")
print()
print(f"  Actual ratio m_s/(m_u+m_d) = {m_s/(m_u+m_d):.4f}")
print(f"  Koide seed ratio = {(2+np.sqrt(3))**4:.4f}")
print(f"  These differ by {abs(m_s/(m_u+m_d) - (2+np.sqrt(3))**4)/((2+np.sqrt(3))**4)*100:.2f}%")
